### ISSUE TITLE
Hi, about the 8 vertex point of the obb?

### ISSUE THREAD

**Issue by zhuhaipeng-byte** [taqu/OBB#1]
Thanks for your great work, but i found your work about computing the obb, there  is short of the the 8 vertex point of the obb? can you write the code about them? have a good day

**Comment by taqu** [comment]
Add fixing for the zero point case. On cases (1-7 points as input), all three functions seem to work well.
"there is short of the the 8 vertex point of the obb" does not mean cases which have 1-7 points as input?

This is the result of a 7 points case.
![obb_dito_simd_0007](https://user-images.githubusercontent.com/362423/188173959-824ad85f-ad90-4726-8198-37b45ee5702b.jpg)

**Comment by zhuhaipeng-byte** [comment]
> Add fixing for the zero point case. On cases (1-7 points as input), all three functions seem to work well. "there is short of the the 8 vertex point of the obb" does not mean cases which have 1-7 points as input?
> 
> This is the result of a 7 points case. ![obb_dito_simd_0007](https://user-images.githubusercontent.com/362423/188173959-824ad85f-ad90-4726-8198-37b45ee5702b.jpg)

okay, thanks a lot.
